### PR TITLE
Fixed Desktop Icon

### PR DESCRIPTION
**Pull request by idietmoran**
This is from issue #34 .

This should be the fix, I laid out my steps in the issue directly. It was a quick one, but I believe the change was made in the `.csproj` file by adding:

```xml
  <PropertyGroup>
    <ApplicationIcon>Icons\IndexerLogo.ico</ApplicationIcon>
  </PropertyGroup>
```

### CODE REVIEW

**Comment by dfs-minded** [comment]
Hi @idietmoran! Thank you once again for the fix!
In this pull request there are some extra lines added by VS, namely 104-106 (local reference path hint) and some other small extra changes.
I can either add manually your code directly to master or you can update your pull request, so that there are only nessesary change left (basically only new line 80).

**Comment by dfs-minded** [comment]
Thank you! No rush:)

**Comment by idietmoran** [comment]
Should be fixed now.

**Comment by dfs-minded** [comment]
Thank you for fast work!

**Pull request merged**
