### PR TITLE
fixed issue where crash would occur if settings was missing

### PR DESCRIPTION
**Pull request by Stateford**
Hello, I made a PR for this a long time ago. I think this will be much cleaner than my previous PR for issue #37.

### CODE REVIEW

**Comment by dfs-minded** [comment]
Hi! This looks much better now. 
A small thing remains: now we do not need to copy UserSettings.xml around for the installer because it will be created automatically. So just delete in Installer/IndexerInstaller.nsi at line 109 "file "UserSettings.xml" and 
in the installerPickingUpScript.cmd at line 8 "copy ... UserSettings.xml".
You were not supposed to know that these deletions should be made, but in this way, you will become more familiar with the deployment process.

After this I will be able to merge, everything looks good to me. Good work!

**Comment by idietmoran** [comment]
Should be good to go now

**Comment by idietmoran** [comment]
reverted and I have the changes in another branch now

**Comment by dfs-minded** [comment]
Hi @Stateford! Finally reviewed and merged. Thanks a lot! 👍

**Pull request merged**
